#!/bin/bash

# Check if Homebrew is installed
if ! command -v brew &> /dev/null && ! command -v /opt/homebrew/bin/brew &> /dev/null; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    # Add Homebrew to PATH
    echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zshrc
    eval $(/opt/homebrew/bin/brew shellenv)
fi

# Verify Homebrew installation
brew doctor || exit 1

# Install MacTeX
brew install --cask mactex || exit 1

# Add TeX to PATH
echo 'export PATH=/Library/TeX/texbin/:$PATH' >> ~/.zshrc

# Verify Asymptote installation
asy -V || exit 1

echo "Asymptote has been successfully installed."
